spring:
  application:
    name: eureka-feigin
eureka:
  client:
    service-url:
      defaultZone: http://192.168.60.141:8003/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8020

feign:
  hystrix:
    enabled: true