server:
  port: 8888

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boss-account?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: DpgZ7jMoro*<
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
# type-aliases-package: com.study.springdatasource.pojo # 注意：对应实体类的路径


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql