spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiajuwei/springCloudConfig
          search-paths: config
          username: xiajuwei@163.com
          password: xj13655675071

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



