eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: eureka-zuul
server:
  port: 8004
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
