spring:
  profiles: peer3
  application:
    name: eureka-server
server:
  port: 8003
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8002/eureka/,http://peer1:8001/eureka/,http://peer4:8004/eureka/
