spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8002
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/,http://peer4:8004/eureka/
