#工程名称
spring:
  application:
    name: eureka-server
  #选择哪一个环境的配置
  #这里可以在每个环境配置redis，数据库（mysql），消息（kafka）等相关的组件的配置
  profiles:
    active: dev
#配置eureka注册中心
eureka:
  server:
    #配置自我保护模式
    enable-self-preservation: true
    #配置Eureka Server清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 4000
  instance:
    #配置与此实例相关联的主机名，是其他实例可以用来进行请求的准确名称
    hostname: localhost
    #显示服务ip地址
    preferIpAddress: true
    #获取服务的ip和端口
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    #配置不将自己注册到eureka注册中心
    register-with-eureka: false
    #配置此客户端不获取eureka服务器注册表上的注册信息
    fetch-registry: false
    serviceUrl:
      #配置默认节点有信息，这里是获取本机的ip和端口来实现，如果不配置，默认会找8761端口，这里配置的是1001端口，因此会报错
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#文档块区分为三个---
---
server:
  port: 8000
spring:
  profiles: dev

#文档块区分为三个---
---
server:
  port: 1002
spring:
  profiles: test

#文档块区分为三个---
---
server:
  port: 1003
spring:
  profiles: prod






