spring:
  profiles: peer1
  application:
    name: eureka-server
server:
  port: 8001
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: true
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8002/eureka/,http://peer3:8003/eureka/,http://peer4:8004/eureka/

