spring:
  application:
    name: service-hi
eureka:
  instance:
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
#    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
#    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://192.168.60.245:8001/eureka/
server:
  port: 8011
