spring:
  profiles: peer2
  application:
    name: eureka-server
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/,http://peer4:8004/eureka/
