package com.study.springdatasource.pojo;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * WARNING:
 * this code is generated by code-generator
 * please DO NOT modify this file
 **/
@Data
public class FinBalanceRecord {
    private long id;
    private Date created;
    private Date modified;
    /**
     * 申请单编号
     **/
    private String appCode;
    /**
     * 申请人姓名
     **/
    private String appName;
    /**
     * 结算金额
     **/
    private BigDecimal balanceAmount;
    /**
     * 结算日期
     **/
    private Date balanceDate;
    /**
     * 应该结算金额
     **/
    private BigDecimal factBalanceAmount;
    /**
     * 本金余额
     **/
    private BigDecimal principalAmount;
    /**
     * 垫付结清金额
     **/
    private BigDecimal payForAmount;
    /**
     * 垫付结清是否需要支付, 0:不需要; 1: 需要
     **/
    private Integer isPayPayfor;
    /**
     * 客户结清金额
     **/
    private BigDecimal customerSettleAmount;
    /**
     * 客户结清是否需要支付, 0:不需要; 1: 需要
     **/
    private Integer isPayCustomer;
    /**
     * 期数
     **/
    private Integer termNo;
    /**
     * 减免金额
     **/
    private BigDecimal derateAmount;
    /**
     * 操作开始期数
     **/
    private Integer balanceStartTermNo;
    /**
     * 操作总期数
     **/
    private Integer totalTermNo;
    /**
     * 结算状态, 0: 正常; 1: 代偿; 2: 回购; 3: 结清
     **/
    private Integer balanceType;
    /**
     * 状态, 0:未完成 ; 1:已完成
     **/
    private Integer status;
    /**
     * 是否允许扣款, 0:禁止; 1:允许; 2:无需扣款
     **/
    private Integer allowCut;
    /**
     * 结清类型,0:正常; 1:收车; 2:诉讼; 3:保险理赔
     **/
    private Integer settleType;
    /**
     * 收款人姓名
     **/
    private String collectionsName;
    /**
     * 收款人账号
     **/
    private String collectionsNo;
    /**
     * 收款人开户行支行
     **/
    private String collectionsAccountBank;
    /**
     * 发起操作原因
     **/
    private String balanceReason;
    /**
     * 支付备注
     **/
    private String payRemark;
    /**
     * 备注
     **/
    private String remark;
    /**
     * 完成结算操作时间
     **/
    private Date finishTime;
    /**
     * 创建人id
     **/
    private Long operatorUserId;
    /**
     * 创建人
     **/
    private String operatorUserName;
    /**
     * 最后修改人id
     **/
    private Long updateOperatorUserId;
    /**
     * 最后修改人姓名
     **/
    private String updateOperatorUserName;
    /**
     * 是否删除, 0: 有效; 1: 删除
     **/
    private Integer isDelete;
    /**
     * 暂存资方实时结清金额
     **/
    private BigDecimal fundSettleAmount;


}
