spring:
  application:
    name: eureka-feigin
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8020

feign:
  hystrix:
    enabled: true