spring:
  application:
    name: eureka-zuul
server:
  port: 8031
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-feigin
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/
